# https://pre-commit.com/

repos:
  - repo: local
    hooks:
      - id: keep-sorted
        name: keep-sorted
        language: golang
        language_version: 1.21.6
        entry: go run .
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.0
    hooks:
      - id: validate_manifest
