# https://pre-commit.com/

repos:
  - repo: https://github.com/google/keep-sorted
    rev: bootstrap-testing
    hooks:
      - id: keep-sorted
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.0
    hooks:
      - id: validate_manifest
