name: Publish Release Artifacts

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            extension: .exe

    runs-on: ${{matrix.os}}

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.23"

      - name: Build
        run: go build -v -o keep-sorted${{matrix.extension}} .
        env:
          GOOS: ${{matrix.goos}}
          GOARCH: ${{matrix.goarch}}
          CGO_ENABLED: "0"

      - name: Test
        run: go test -v ./...

      - name: Upload Artifacts to Release
        run: |
          echo Uploading ${{matrix.goos}}_${{matrix.goarch}} artifact for ${GITHUB_REF_NAME}
          mv keep-sorted${{matrix.extension}} keep-sorted_${{matrix.goos}}_${{matrix.goarch}}${{matrix.extension}}
          gh release upload ${GITHUB_REF_NAME} keep-sorted_${{matrix.goos}}_${{matrix.goarch}}${{matrix.extension}} --clobber
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
